const teaList = [
  "branco",
  "mate",
  "preto",
  "verde",
  "de alecrim",
  "de amora",
  "de anis estrelado",
  "de boldo",
  "de camomila",
  "de canela",
  "de capim limão",
  "de carqueja",
  "de cavalinha",
  "de dente-de-leão",
  "de erva-cidreira",
  "de erva-doce",
  "de espinheira santa",
  "de eucalipto",
  "de graviola",
  "de guaco",
  "de hibisco",
  "de hortelã",
  "de gengibre",
  "de malva",
  "de melissa",
  "de menta",
  "de sete ervas",
  "de oliveira",
  "de sálvia",
];

module.exports = Object.freeze({ teaList });
